sudo: false
language: go
go_import_path: shanhu.io/misc

go:
    - "1.13"

install:
    - go get ./...
    - go get shanhu.io/sml/cmd/smake

script:
    - test -z `gofmt -s -l .`
    - go test ./...
    - smake
